json.extract! listing,
  :id,
  :host_id,
  :name,
  :description,
  :address,
  :daily_cost,
  :max_guest,
  :lat,
  :lng,
  :is_camping,
  :allow_pets,
  :is_wifi,
  :is_toilets,
  :is_showers,
  :is_biking,
  :is_fishing,
  :is_paddling,
  :is_horseback_riding,
  :is_surfing,
  :is_climbing,
  :check_in_after,
  :check_out_before,
  :icon_url
  json.host_name listing.host.first_name
